version: '3'
services:
  django:
    build: .
    env_file:
      - .env
      - .env.django.secret
    ports:
      - "8000:8000"
    volumes:
      - .:/django/
    depends_on:
      - redis
      - postgres
      - smtpd
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  postgres:
    image: postgres:13
    restart: always
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  smtpd:
    build:
      context: .
      dockerfile: Dockerfile.smtpd
    expose:
      - "1025"
